MCU = RP2040
BOOTLOADER = rp2040

# 機能設定
SPLIT_KEYBOARD = yes
OLED_ENABLE = yes
# ENCODER_ENABLE = yes
LTO_ENABLE = yes
TAP_DANCE_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes

# 旧：SERIAL_DRIVER = vendor （これを消して、以下の2行に差し替えます）
SPLIT_TRANSPORT = custom
